In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2 , 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [5]:
a3.shape

(2, 3, 3)



Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.


In [9]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.dtype, type(a1)

((3,), dtype('int32'), numpy.ndarray)

In [10]:
# Attributes of 2-dimensional array
a2.shape, a2.dtype, type(a2)

((2, 3), dtype('int32'), numpy.ndarray)

In [11]:
# Attributes of 3-dimensional array
a3.shape, a3.dtype, type(a3)

((2, 3, 3), dtype('int32'), numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df3 = pd.DataFrame(a2)
df3

0  1  2
0  1  2  3
1  4  5  6

In [15]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
# Create an array within a range of 0 and 100 with step 3
random_array_1 = np.random.randint(0,100,3)
random_array_1

array([89, 89, 73])

In [18]:
random_array_1

array([55, 66, 89])

In [22]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array_2 = np.random.randint(0,10, size=(7,2))
random_array_2

array([[4, 5],
       [8, 4],
       [9, 4],
       [9, 3],
       [4, 6],
       [4, 5],
       [3, 9]])

In [24]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_3 = np.random.random(size=(3,5))
random_array_3

array([[0.79238253, 0.59118208, 0.43640564, 0.81401912, 0.78231955],
       [0.21403612, 0.42311263, 0.37930097, 0.2922511 , 0.34697361],
       [0.30811831, 0.31567723, 0.88390362, 0.82419771, 0.65425094]])

In [28]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_4 = np.random.randint(0, 10, size = (4, 6))
random_array_4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])



Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?


In [32]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_5 = np.random.randint(1, 10, size = (3, 7))

# Find the unique numbers in the array you just created
random_array_5, np.unique(random_array_5)

(array([[2, 5, 8, 9, 9, 1, 9],
        [7, 9, 8, 1, 8, 8, 3],
        [1, 8, 3, 3, 1, 5, 7]]),
 array([1, 2, 3, 5, 7, 8, 9]))

In [34]:
# Find the 0'th index of the latest array you created
random_array_5[0]

array([2, 5, 8, 9, 9, 1, 9])

In [35]:
# Get the first 2 rows of latest array you created
random_array_5[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [36]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_5[:2, :2]

array([[2, 5],
       [7, 9]])

In [37]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_6 = np.random.randint(0,10,size=(3,5))
ones = np.ones((3,5))

In [39]:
random_array_6

array([[9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7],
       [4, 2, 7, 5, 2]])

In [40]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
# Add the two arrays together
random_array_6 + ones

array([[10.,  9.,  7.,  9.,  8.],
       [ 2.,  1.,  7.,  7.,  8.],
       [ 5.,  3.,  8.,  6.,  3.]])

In [41]:
# Create another array of ones of shape (5, 3)
ones_1 = np.ones((5,3))

In [42]:
# Try add the array of ones and the other most recent array together
random_array_6 + ones_1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 



When you try the last cell, it produces an error. Why do think this is?

How would you fix it?


In [43]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))

In [44]:
# Subtract the new array of ones from the other most recent array
random_array_6 - ones

array([[ 8.,  7.,  5.,  7.,  6.],
       [ 0., -1.,  5.,  5.,  6.],
       [ 3.,  1.,  6.,  4.,  1.]])

In [45]:
# Multiply the ones array with the latest array
random_array_6 * ones

array([[9., 8., 6., 8., 7.],
       [1., 0., 6., 6., 7.],
       [4., 2., 7., 5., 2.]])

In [48]:
# Take the latest array to the power of 2 using '**'
random_array_6 ** 2

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]])

In [49]:
# Do the same thing with np.square()
np.square(random_array_6)

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]])

In [50]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_6)

5.2

In [51]:
# Find the maximum of the latest array using np.max()
np.max(random_array_6)

9

In [52]:
# Find the minimum of the latest array using np.min()
np.min(random_array_6)

0

In [53]:
# Find the standard deviation of the latest array
np.std(random_array_6)

2.6882460204874605

In [54]:
# Find the variance of the latest array
np.var(random_array_6)

7.2266666666666675

In [55]:
# Reshape the latest array to (3, 5, 1)
random_array_6 = random_array_6.reshape(3,5,1)

In [56]:
random_array_6

array([[[9],
        [8],
        [6],
        [8],
        [7]],

       [[1],
        [0],
        [6],
        [6],
        [7]],

       [[4],
        [2],
        [7],
        [5],
        [2]]])

In [62]:
random_array_6

array([[[9, 1, 4],
        [8, 0, 2],
        [6, 6, 7],
        [8, 6, 5],
        [7, 7, 2]]])

In [59]:
# Transpose the latest array
random_array_6 = random_array_6.T
random_array_6

array([[[9],
        [8],
        [6],
        [8],
        [7]],

       [[1],
        [0],
        [6],
        [6],
        [7]],

       [[4],
        [2],
        [7],
        [5],
        [2]]])

What does the transpose do?

In [63]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_7 = np.random.randint(0,10,size=(3,3))
random_array_8 = np.random.randint(0,10,size=(3,2))


In [64]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_7, random_array_8)

array([[ 42,   4],
       [ 40,  18],
       [162,  93]])

In [65]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_9 = np.random.randint(0,10,size=(4,3))
random_array_10 = np.random.randint(0,10,size=(4,3))


In [66]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_9, random_array_10)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [67]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_array_9, random_array_10.T)

array([[ 39,  77,  18,  60],
       [ 63, 114,  36, 105],
       [ 49, 106,  36,  79],
       [ 73, 127,   6, 104]])



Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on np.dot() may help, as well as reading Math is Fun's guide on the dot product.

Let's now compare arrays.


In [68]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
r_a_1 = np.random.randint(0,10,size=(4,3))
r_a_2 = np.random.randint(0,10,size=(4,3))


In [70]:
# Compare the two arrays with '>'
r_a_1 > r_a_2

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

What happens when you compare the arrays with >?

In [71]:
# Compare the two arrays with '>='
r_a_1 >= r_a_2

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [72]:
# Find which elements of the first array are greater than 7
r_a_1 > 7

array([[ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [73]:
# Which parts of each array are equal? (try using '==')
r_a_1 == r_a_2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [74]:
# Sort one of the arrays you just created in ascending order
np.sort(r_a_1)

array([[2, 6, 8],
       [5, 7, 8],
       [0, 2, 4],
       [5, 7, 9]])

In [75]:
# Sort the indexes of one of the arrays you just created
np.argsort(r_a_1)

array([[1, 2, 0],
       [0, 1, 2],
       [1, 2, 0],
       [2, 1, 0]], dtype=int64)

In [80]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(r_a_1)

9

In [81]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(r_a_1)

7

In [82]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(r_a_1, axis = 1)

array([0, 2, 0, 0], dtype=int64)

In [83]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(r_a_1, axis = 0)

array([2, 2, 2], dtype=int64)

In [85]:
# Create an array of normally distributed random numbers
array = np.random.normal(0,1,10)
array

array([ 1.40279431, -1.40185106,  0.58685709,  2.19045563, -0.99053633,
       -0.56629773,  0.09965137, -0.50347565, -1.55066343,  0.06856297])

In [86]:
# Create an array with 10 evenly spaced numbers between 1 and 100
array = np.random.normal(0,100,10)
array

array([-106.23037137,   47.35924306,  -91.94242342,  154.9934405 ,
        -78.32532923,  -32.20615162,   81.35172174, -123.08643164,
         22.74599346,  130.71427543])